# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 06:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sink_id', models.IntegerField(blank=True, null=True)),
                ('sink_type', models.CharField(blank=True, choices=[('CATCHMENT', 'Catchment Basin'), ('SINKHOLE', 'Sinkhole'), ('OTHER', 'Other')], max_length=20)),
                ('dem_check', models.IntegerField(blank=True, null=True)),
                ('img_check', models.IntegerField(blank=True, null=True)),
                ('evidence', models.CharField(blank=True, max_length=1, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('in_nfhl', models.NullBooleanField()),
                ('in_row', models.NullBooleanField()),
                ('comment', models.TextField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
