# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='bm_aerial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sink',
            name='bm_hs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sink',
            name='bm_tpi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sink',
            name='bm_usgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sink',
            name='confidence',
            field=models.CharField(blank=True, choices=[('PROBABLE', 'Probable'), ('POSSIBLE', 'Possible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='sink_type',
            field=models.CharField(blank=True, choices=[('CATCHMENT', 'Catchment Basin'), ('SINKHOLE', 'Sinkhole'), ('QUARRY', 'Quarry'), ('DC', 'Ditch/Culvert'), ('FOUNDATION', 'Building Foundation'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
    ]
