# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 15:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='sink',
            name='sink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sink',
            name='dem_check',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='evidence',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='sink',
            name='img_check',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='type',
            field=models.CharField(blank=True, choices=[('CATCHMENT', 'Catchment Basin'), ('SINKHOLE', 'Sinkhole'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
