# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='dem_check',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='img_check',
            field=models.IntegerField(null=True),
        ),
    ]
