# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0002_auto_20170919_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='comment',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='evidence',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
