# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0003_auto_20170919_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sink',
            old_name='type',
            new_name='sink_type',
        ),
    ]
