# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0003_auto_20170918_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='sink_id',
            field=models.IntegerField(null=True),
        ),
    ]
