# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0006_sink_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='event_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
