# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0007_sink_event_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='field_chk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sink',
            name='field_eval',
            field=models.CharField(blank=True, choices=[('PROBABLE', 'Probable'), ('POSSIBLE', 'Possible')], max_length=20, null=True),
        ),
    ]
