# Generated by Django 3.2 on 2022-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0012_auto_20210213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='location_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location Method'),
        ),
        migrations.AlterField(
            model_name='well',
            name='static_depth_above_below',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Static Depth Above Below'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Well Status'),
        ),
    ]
