# Generated by Django 3.2.14 on 2023-01-13 22:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0013_auto_20221130_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
