# Generated by Django 3.2.14 on 2023-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0014_fractureline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractureline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sink',
            name='in_nfhl',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='in_row',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='townunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
