# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0002_auto_20170918_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='elevation',
            field=models.FloatField(null=True),
        ),
    ]
