# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0004_sink_sink_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sink',
            name='id',
        ),
        migrations.AlterField(
            model_name='sink',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sink',
            name='sink_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
