# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0005_auto_20170918_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='evidence',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='sink',
            name='type',
            field=models.CharField(blank=True, choices=[('CATCHMENT', 'Catchment Basin'), ('SINKHOLE', 'Sinkhole'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
