# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0006_auto_20170918_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sink',
            name='dem_check',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='img_check',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
