# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 04:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0007_auto_20170918_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
