# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspkarst', '0008_sink_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sink',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sink',
            name='sink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
